name: Env-Variable

on:
  workflow_dispatch:

jobs:
  display:
    runs-on: ubuntu-latest
    steps:
       - run: |
              echo ${{ secrets.APIKEY }}
              echo ${{ runner.os }}
              echo ${{ vars.API }}
